version: '3.7'
services:
  redis-dev:
    container_name: redis-dev
    image: redis:7.0.12
    restart: always
    networks:
      - default
    ports:
      - "6379:6379"
    volumes:
      - redis-dev:/data
  desti-database-dev:
    image: postgres:14
    container_name: "database-dev"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_DB_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - ${POSTGRES_DB_PORT}:5432
    volumes:
      - data-dev:/var/lib/postgresql/data
volumes:
  data-dev:
  redis-dev:
    driver: local
