version: '1:0:2'
services:
  placewizdata-dev:
    image: postgres:14
    container_name: placewizdata-dev
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_DB_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - ${POSTGRES_DB_PORT}:5432
    volumes:
      - placewizdata:/var/lib/postgresql/data
    networks:
      -placewiz:
volumes:
  placewizdata:
networks:
  -placewiz:
