version: '3.7'
services:
  desti-database-dev:
    image: postgres:14
    container_name: ${POSTGRES_DB_HOST}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_DB_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - ${POSTGRES_DB_PORT}:5432
    volumes:
      - desti-dev-data:/var/lib/postgresql/data
volumes:
  desti-dev-data:
