version: '1:0:2'
services:
  destidata-dev:
    image: postgres:14
    container_name: destidata-dev
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_DB_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - ${POSTGRES_DB_PORT}:5432
    volumes:
      - destidata:/var/lib/postgresql/data
    networks:
      -desti:
volumes:
  destidata:
networks:
  -desti:
