version: '1.0.2'
services:
  placewiz-db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${CONTAINER_NAME}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
#host.docker.internal
