version: '3.7'
services:
  desti-db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_DB_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - ${POSTGRES_DB_PORT}:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.db
      - desti-data:/var/lib/postgresql/data
  desti-nestjs:
    image: desti-nestjs-image
    depends_on:
      - desti-db
    ports:
      - ${PORT}:3001
volumes:
  desti-data:
